-- Phase 1a: platform core.
--
-- Denormalizes workspaceId onto every tenant-owned table, adds the durable
-- workflow tables (Operation, ProviderCall, RawSnapshot, UsageEvent,
-- AuditEvent, Entitlement, FeatureFlag, RateLimitBucket), and adds
-- repetitionIndex to PromptRun so a prompt can be sampled more than once.
--
-- Hand-reviewed. The ADD COLUMN ... NOT NULL statements below for the six
-- workspaceId columns were generated by `prisma migrate diff` against an
-- empty database and are UNSAFE as-is: Competitor has real rows in every
-- environment. Each is manually split into add-nullable -> backfill ->
-- set-not-null. Prompt, AnalysisBatch, PromptRun, RunAnalysis, and Source
-- have zero rows today, so their backfills are no-ops, but are written the
-- same way for correctness if that ever changes before this migration runs.

-- CreateEnum
CREATE TYPE "BrandStatus" AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "CompetitorSource" AS ENUM ('AI_DISCOVERED', 'SERP_DISCOVERED', 'USER_ADDED');

-- CreateEnum
CREATE TYPE "CompetitorStatus" AS ENUM ('CANDIDATE', 'ACCEPTED', 'IGNORED', 'PINNED');

-- CreateEnum
CREATE TYPE "OperationKind" AS ENUM ('BRAND_DISCOVERY', 'PROMPT_GENERATION', 'BENCHMARK_BATCH', 'SERP_HUNT', 'THREAT_SCORE', 'CRAWL', 'OPPORTUNITY_DETECT', 'CONTENT_BRIEF', 'CONTENT_DRAFT', 'PUBLICATION', 'GSC_IMPORT', 'WEEKLY_REPORT');

-- CreateEnum
CREATE TYPE "OperationStatus" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ProviderCapability" AS ENUM ('GENERATION', 'BENCHMARK', 'SERP', 'KEYWORDS', 'BACKLINKS', 'CRAWL', 'ANALYTICS', 'PUBLISHING', 'NOTIFICATION');

-- CreateEnum
CREATE TYPE "StorageDriver" AS ENUM ('DB', 'S3');

-- CreateEnum
CREATE TYPE "RetentionClass" AS ENUM ('STANDARD', 'EXTENDED', 'LEGAL_HOLD');

-- DropIndex
DROP INDEX "PromptRun_batchId_promptId_provider_model_key";

-- AlterTable
ALTER TABLE "Brand" ADD COLUMN     "status" "BrandStatus" NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE "Competitor" ADD COLUMN     "acceptedAt" TIMESTAMP(3),
ADD COLUMN     "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "source" "CompetitorSource" NOT NULL DEFAULT 'AI_DISCOVERED',
ADD COLUMN     "status" "CompetitorStatus" NOT NULL DEFAULT 'ACCEPTED',
ADD COLUMN     "workspaceId" TEXT;

-- Backfill: Competitor has real rows, so this is not a no-op.
UPDATE "Competitor" c
SET "workspaceId" = b."workspaceId"
FROM "Brand" b
WHERE b."id" = c."brandId";

ALTER TABLE "Competitor" ALTER COLUMN "workspaceId" SET NOT NULL;

-- AlterTable
ALTER TABLE "Prompt" ADD COLUMN     "workspaceId" TEXT;

UPDATE "Prompt" p
SET "workspaceId" = b."workspaceId"
FROM "Brand" b
WHERE b."id" = p."brandId";

ALTER TABLE "Prompt" ALTER COLUMN "workspaceId" SET NOT NULL;

-- AlterTable
ALTER TABLE "AnalysisBatch" ADD COLUMN     "workspaceId" TEXT;

UPDATE "AnalysisBatch" ab
SET "workspaceId" = b."workspaceId"
FROM "Brand" b
WHERE b."id" = ab."brandId";

ALTER TABLE "AnalysisBatch" ALTER COLUMN "workspaceId" SET NOT NULL;

-- AlterTable
ALTER TABLE "PromptRun" ADD COLUMN     "locale" TEXT,
ADD COLUMN     "providerCallId" TEXT,
ADD COLUMN     "providerVersion" TEXT,
ADD COLUMN     "rawSnapshotId" TEXT,
ADD COLUMN     "repetitionIndex" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "workspaceId" TEXT;

-- Backfill from AnalysisBatch, which was populated above in this same migration.
UPDATE "PromptRun" pr
SET "workspaceId" = ab."workspaceId"
FROM "AnalysisBatch" ab
WHERE ab."id" = pr."batchId";

ALTER TABLE "PromptRun" ALTER COLUMN "workspaceId" SET NOT NULL;

-- AlterTable
ALTER TABLE "RunAnalysis" ADD COLUMN     "workspaceId" TEXT;

-- Backfill from PromptRun, which was populated above in this same migration.
UPDATE "RunAnalysis" ra
SET "workspaceId" = pr."workspaceId"
FROM "PromptRun" pr
WHERE pr."id" = ra."promptRunId";

ALTER TABLE "RunAnalysis" ALTER COLUMN "workspaceId" SET NOT NULL;

-- AlterTable
-- promptRunId becomes optional here: a Source can now anchor to a
-- ProviderCall instead, which brand discovery (Phase 1a) needs since it has
-- no PromptRun to attach to. See the Source model comment in schema.prisma.
ALTER TABLE "Source" ADD COLUMN     "providerCallId" TEXT,
ADD COLUMN     "workspaceId" TEXT,
ALTER COLUMN "promptRunId" DROP NOT NULL;

UPDATE "Source" s
SET "workspaceId" = pr."workspaceId"
FROM "PromptRun" pr
WHERE pr."id" = s."promptRunId";

ALTER TABLE "Source" ALTER COLUMN "workspaceId" SET NOT NULL;

-- CreateTable
CREATE TABLE "Operation" (
    "id" TEXT NOT NULL,
    "kind" "OperationKind" NOT NULL,
    "status" "OperationStatus" NOT NULL DEFAULT 'PENDING',
    "progressCurrent" INTEGER NOT NULL DEFAULT 0,
    "progressTotal" INTEGER NOT NULL DEFAULT 0,
    "idempotencyKey" TEXT NOT NULL,
    "inngestRunId" TEXT,
    "actorUserId" TEXT,
    "errorCode" TEXT,
    "errorMessage" TEXT,
    "metadata" JSONB,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "brandId" TEXT,

    CONSTRAINT "Operation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProviderCall" (
    "id" TEXT NOT NULL,
    "capability" "ProviderCapability" NOT NULL,
    "provider" TEXT NOT NULL,
    "providerVersion" TEXT,
    "requestId" TEXT,
    "status" "RunStatus" NOT NULL DEFAULT 'PENDING',
    "requestedAt" TIMESTAMP(3) NOT NULL,
    "completedAt" TIMESTAMP(3),
    "httpStatus" INTEGER,
    "costUnits" DECIMAL(12,6),
    "currency" TEXT,
    "inputTokens" INTEGER,
    "outputTokens" INTEGER,
    "errorCode" TEXT,
    "errorMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "operationId" TEXT,
    "rawSnapshotId" TEXT,

    CONSTRAINT "ProviderCall_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RawSnapshot" (
    "id" TEXT NOT NULL,
    "driver" "StorageDriver" NOT NULL,
    "objectKey" TEXT NOT NULL,
    "sha256" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "byteSize" INTEGER NOT NULL,
    "retentionClass" "RetentionClass" NOT NULL DEFAULT 'STANDARD',
    "expiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,

    CONSTRAINT "RawSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RawSnapshotBlob" (
    "id" TEXT NOT NULL,
    "bytes" BYTEA NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "snapshotId" TEXT NOT NULL,

    CONSTRAINT "RawSnapshotBlob_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UsageEvent" (
    "id" TEXT NOT NULL,
    "meter" TEXT NOT NULL,
    "quantity" DECIMAL(14,4) NOT NULL,
    "idempotencyKey" TEXT NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "operationId" TEXT,

    CONSTRAINT "UsageEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditEvent" (
    "id" TEXT NOT NULL,
    "actorUserId" TEXT,
    "action" TEXT NOT NULL,
    "targetType" TEXT NOT NULL,
    "targetId" TEXT NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,

    CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Entitlement" (
    "id" TEXT NOT NULL,
    "plan" TEXT NOT NULL DEFAULT 'beta',
    "limits" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "workspaceId" TEXT NOT NULL,

    CONSTRAINT "Entitlement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FeatureFlag" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "workspaceId" TEXT NOT NULL,

    CONSTRAINT "FeatureFlag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RateLimitBucket" (
    "key" TEXT NOT NULL,
    "windowStart" TIMESTAMP(3) NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RateLimitBucket_pkey" PRIMARY KEY ("key")
);

-- CreateIndex
CREATE UNIQUE INDEX "Operation_idempotencyKey_key" ON "Operation"("idempotencyKey");

-- CreateIndex
CREATE INDEX "Operation_workspaceId_createdAt_idx" ON "Operation"("workspaceId", "createdAt");

-- CreateIndex
CREATE INDEX "Operation_workspaceId_status_idx" ON "Operation"("workspaceId", "status");

-- CreateIndex
CREATE INDEX "Operation_brandId_idx" ON "Operation"("brandId");

-- CreateIndex
CREATE INDEX "ProviderCall_workspaceId_provider_createdAt_idx" ON "ProviderCall"("workspaceId", "provider", "createdAt");

-- CreateIndex
CREATE INDEX "ProviderCall_operationId_idx" ON "ProviderCall"("operationId");

-- CreateIndex
CREATE INDEX "RawSnapshot_workspaceId_createdAt_idx" ON "RawSnapshot"("workspaceId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "RawSnapshot_workspaceId_sha256_key" ON "RawSnapshot"("workspaceId", "sha256");

-- CreateIndex
CREATE UNIQUE INDEX "RawSnapshotBlob_snapshotId_key" ON "RawSnapshotBlob"("snapshotId");

-- CreateIndex
CREATE UNIQUE INDEX "UsageEvent_idempotencyKey_key" ON "UsageEvent"("idempotencyKey");

-- CreateIndex
CREATE INDEX "UsageEvent_workspaceId_meter_occurredAt_idx" ON "UsageEvent"("workspaceId", "meter", "occurredAt");

-- CreateIndex
CREATE INDEX "AuditEvent_workspaceId_createdAt_idx" ON "AuditEvent"("workspaceId", "createdAt");

-- CreateIndex
CREATE INDEX "AuditEvent_workspaceId_targetType_targetId_idx" ON "AuditEvent"("workspaceId", "targetType", "targetId");

-- CreateIndex
CREATE UNIQUE INDEX "Entitlement_workspaceId_key" ON "Entitlement"("workspaceId");

-- CreateIndex
CREATE UNIQUE INDEX "FeatureFlag_workspaceId_key_key" ON "FeatureFlag"("workspaceId", "key");

-- CreateIndex
CREATE INDEX "Competitor_workspaceId_idx" ON "Competitor"("workspaceId");

-- CreateIndex
CREATE INDEX "Prompt_workspaceId_idx" ON "Prompt"("workspaceId");

-- CreateIndex
CREATE INDEX "AnalysisBatch_workspaceId_idx" ON "AnalysisBatch"("workspaceId");

-- CreateIndex
CREATE INDEX "PromptRun_workspaceId_idx" ON "PromptRun"("workspaceId");

-- CreateIndex
CREATE INDEX "PromptRun_providerCallId_idx" ON "PromptRun"("providerCallId");

-- CreateIndex
CREATE UNIQUE INDEX "PromptRun_batchId_promptId_provider_model_repetitionIndex_key" ON "PromptRun"("batchId", "promptId", "provider", "model", "repetitionIndex");

-- CreateIndex
CREATE INDEX "RunAnalysis_workspaceId_idx" ON "RunAnalysis"("workspaceId");

-- CreateIndex
CREATE INDEX "Source_workspaceId_idx" ON "Source"("workspaceId");

-- CreateIndex
CREATE INDEX "Source_providerCallId_idx" ON "Source"("providerCallId");

-- AddForeignKey
ALTER TABLE "Competitor" ADD CONSTRAINT "Competitor_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Prompt" ADD CONSTRAINT "Prompt_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AnalysisBatch" ADD CONSTRAINT "AnalysisBatch_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PromptRun" ADD CONSTRAINT "PromptRun_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PromptRun" ADD CONSTRAINT "PromptRun_providerCallId_fkey" FOREIGN KEY ("providerCallId") REFERENCES "ProviderCall"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PromptRun" ADD CONSTRAINT "PromptRun_rawSnapshotId_fkey" FOREIGN KEY ("rawSnapshotId") REFERENCES "RawSnapshot"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RunAnalysis" ADD CONSTRAINT "RunAnalysis_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Source" ADD CONSTRAINT "Source_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Source" ADD CONSTRAINT "Source_providerCallId_fkey" FOREIGN KEY ("providerCallId") REFERENCES "ProviderCall"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Operation" ADD CONSTRAINT "Operation_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Operation" ADD CONSTRAINT "Operation_brandId_fkey" FOREIGN KEY ("brandId") REFERENCES "Brand"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProviderCall" ADD CONSTRAINT "ProviderCall_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProviderCall" ADD CONSTRAINT "ProviderCall_operationId_fkey" FOREIGN KEY ("operationId") REFERENCES "Operation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProviderCall" ADD CONSTRAINT "ProviderCall_rawSnapshotId_fkey" FOREIGN KEY ("rawSnapshotId") REFERENCES "RawSnapshot"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RawSnapshot" ADD CONSTRAINT "RawSnapshot_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RawSnapshotBlob" ADD CONSTRAINT "RawSnapshotBlob_snapshotId_fkey" FOREIGN KEY ("snapshotId") REFERENCES "RawSnapshot"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UsageEvent" ADD CONSTRAINT "UsageEvent_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UsageEvent" ADD CONSTRAINT "UsageEvent_operationId_fkey" FOREIGN KEY ("operationId") REFERENCES "Operation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Entitlement" ADD CONSTRAINT "Entitlement_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeatureFlag" ADD CONSTRAINT "FeatureFlag_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
